artifact_uri: /Users/sahilbodkhe/Desktop/Experiment4/SYDE770/runs/mlflow/283939179369314934/4d12216f8ff248eea570fcceee7b307b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '283939179369314934'
lifecycle_stage: active
run_id: 4d12216f8ff248eea570fcceee7b307b
run_name: train9
run_uuid: 4d12216f8ff248eea570fcceee7b307b
source_name: ''
source_type: 4
source_version: ''
start_time: 1741819158787
status: 1
tags: []
user_id: sahilbodkhe
